import Head from 'next/head'

import 'bootstrap/dist/css/bootstrap.min.css';

import { Container } from 'react-bootstrap';
import LoopsMap from '../../components/LoopsMap/LoopsMap';
import Nav from '../../components/Nav';
import Loops from '../../components/Loops';

export default function Gallery() {
    return (
        <>
          <Head>
            <title>shAI Compendium</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Nav />
          <Container className="mt-5 pt-5 mb-5">
          <LoopsMap />
          </Container> 
        </>
      )
}