import Head from 'next/head';
import { useRef, useEffect } from "react";

import 'bootstrap/dist/css/bootstrap.min.css';

import { Container, Row, Col, Card, Figure } from 'react-bootstrap';
import Nav from '../../components/Sub';
import styles from '@/styles/Home.module.css';
import classNames from 'classnames';

import { construct } from '../../components/Loops/Loops.render';
import ArxivTable from '../../components/arXivTable';
import * as d3 from "d3";

const data = {
  loop: []
}

for(let i = 0; i < 6; i++) {
  let choice = Math.random();
  if (choice > 0.5) {
    data.loop.push({
      actor: "human",
      index: i,
    })
  } else {
    data.loop.push({
      actor: "algorithm",
      index: 6 - i,
    })
  }
}

export default function Home() {
  const svgEl = useRef();
  
  const height = 200;
  const radius = 50;
  const labels = true;
  
  useEffect(() => {
    construct(svgEl.current, data.loop, svgEl.current.clientWidth, height, radius, labels);
  }, []);
  
  return (
    <>
    <Head>
    <title>shAI Compendium</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    <Nav/>
    <Container fluid className={styles.heroContainer}>
    <Row>
    <Col md={{ span: 12 }}>
    <h1 className={"text-center"}>shAI Compendium</h1>
    <svg ref={svgEl} width="100%" height={height} className={styles.homeSvg}></svg>
    </Col>
    </Row>
    </Container>

    <Container className={classNames("pt-5 mt-4 pb-5 mb-5", styles.homeContainer)} >
      <Row>
        <Col><blockquote className={classNames("mb-5", styles.intro)}>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</blockquote></Col>
      </Row>
    <Row>
    <Col md={{ span: 4 }}>
    <Figure><Figure.Image
    width={170}
    height={200}
    alt="600x400"
    src="https://placehold.co/170x200"
    />
    <Figure.Caption className={styles.caption}>
    Nulla vitae elit libero, a pharetra augue mollis interdum.
    </Figure.Caption></Figure>
    </Col>
    <Col md={{ span: 8 }}>
    <ArxivTable className={"mt-2"}/>
    </Col>
    </Row>
    </Container> 
    </>
    )
  }
  