import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';

import { Container } from 'react-bootstrap';
import PlaceLoops from '../../components/PlaceLoops';
import Nav from '../../components/Nav';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Container className="mt-5 pt-5 mb-5">
      <PlaceLoops />
      </Container> 
    </>
  )
}
