import Head from 'next/head'
import Image from 'next/image'
import data from '../../data/data';
import Link from 'next/link';
import { useEffect } from 'react';

import styles from '@/styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import { Container, Row, Col, ListGroup } from 'react-bootstrap';
import PlaceLoops from '../../components/PlaceLoops';
import Nav from '../../components/Sub';
import Legend from '../../components/Legend';

const count = data.length;
const alpha = Array.from(Array(26)).map((e, i) => i + 65);
const alphabet = alpha.map((x) => String.fromCharCode(x));

export default function Home() {
  
  return (
    <>
    <Head>
    <title>shAI Compendium</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    {console.log(count)}
    <Nav count = { count }/>
    <Container fluid className="mt-3 pb-5 mb-5">
    <Legend />
    <Row>
    <Col md={{ span: 2 }}>
    <ListGroup variant="flush" as="ul" className={ styles.indexBox }>
      {
        alphabet.map((a) => (<ListGroup.Item className={ styles.index } key={a} ><Link href={"#" + a}>{a}</Link></ListGroup.Item>))
      }
    </ListGroup>
      </Col>
      <Col md={{ span: 10 }}>
      <PlaceLoops cards={ data }/>
      </Col>
      </Row>
      </Container> 
      </>
      )
    }