import Head from 'next/head'
import Image from 'next/image'
import data from '../../data/data';

import styles from '@/styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import { Container } from 'react-bootstrap';
import PlaceLoops from '../../components/PlaceLoops';
import Nav from '../../components/Sub';
import Legend from '../../components/Legend';

const count = data.length;

export default function Home() {
  return (
    <>
      <Head>
        <title>shAI Compendium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {console.log(count)}
      <Nav count = { count }/>
      <Container fluid className="mt-3 pb-5 mb-5">
      <Legend />
      <PlaceLoops cards={ data }/>
      </Container> 
    </>
  )
}
