import Head from 'next/head'
import data from '../../data/data';
import Link from 'next/link';
import { useEffect } from 'react';

import * as d3 from "d3";

import styles from '@/styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';

import { Container, Row, Col, Table, ListGroup } from 'react-bootstrap';
import Nav from '../../components/Sub';

const count = data.length;
let humanTasks = [];
let algoTasks = [];

let promisesList = [];

data.forEach(d => {
  d.value.promises.forEach(p => {
    promisesList.push(p);
  })
});

let promises = promisesList.filter((value, index, array) => array.indexOf(value) === index)

data.forEach(d => {
  if (d.value.promises.includes("Speed")) {
    let hList = d.loop.filter(e => e.actor === "human" && e.type);
    hList.forEach(t => humanTasks.push(t));

    let aList = d.loop.filter(e => e.actor === "algorithm" && e.type);
    aList.forEach(t => algoTasks.push(t));
  }
});

humanTasks.sort((a, b) => d3.ascending(a.type, b.type))
algoTasks.sort((a, b) => d3.ascending(a.title, b.title))

export default function Home() { 
  
  return (
    <>
    <Head>
    <title>shAI Compendium</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    {console.log(count)}
    <Nav count = { count }/>
    <Container fluid className="mt-3 pb-5 mb-5">
    <Row>
    <Col md={{ span: 2 }}>
      <ListGroup>
        {
          promises.map(p => (<ListGroup.Item href={`#${p}`} key={p}>{p}</ListGroup.Item>))
        }
      </ListGroup>
    </Col>
    <Col md={{ span: 5 }}>
    <h4>Tasks performed by humans</h4>
    <Table striped>
      <thead>
        <tr>
          <th>Human</th>
          <th>Task</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {
          humanTasks.map(task => (<tr><td>{task.type}</td><td>{task.title}</td><td>{task.label}</td></tr>))
        }
      </tbody>
    </Table>  
    </Col>
    <Col md={{ span: 5 }}>
    <h4>Tasks performed by algorithms</h4>
    <Table striped>
    <thead>
        <tr>
          <th>Task</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {
          algoTasks.map(task => (<tr><td>{task.title}</td><td>{task.label}</td></tr>))
        }
      </tbody>
    </Table>
    </Col>
    </Row>
    </Container> 
    </>
    )
  }